# Generated by Django 6.0.5 on 2026-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_logic', '0002_create_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
